### ISSUE TITLE
bug: known vocabulary leaderboard number doesn't match Learn page known vocab number

### ISSUE THREAD

**Issue by pm215** [jpdb-io/issue-tracker#212] opened 2022-10-08 10:52 UTC
On my Learn page it says:

Total known non-redundant vocabulary: 13741

But on the new 'known vocabulary' leaderboard my entry is:

pm215
This is you!
1191

Surely these two numbers should be the same, not an order of magnitude different?

Alternatively, if the 'known vocab' leaderboard isn't actually ranking known vocab, perhaps it should have a different name. Documentation of what it's ranking would be helpful too, I think.

**Comment by koute** [comment] 2022-10-08 10:56
This is not a bug. The known words leaderboard deliberately only includes non-redundant known words which are *not* marked as never forget. (Otherwise you could just pick the biggest deck in the database, mark it as known, and instantly jump to the 1st place.)

I agree that we should document this somewhere.

**Closed as completed by koute** 2022-10-08 10:56 UTC

**Comment by pm215** [comment] 2022-10-09 20:36
I mark words as "never forget" exactly *because* I know them, so this seems a little unfair on people who haven't been using jpdb as their exclusive source of vocab knowledge since the year dot... I can see the rationale for the behaviour, though.
